/**
 * ============================================================
 * SEBAShield
 * Link Analysis Result Screen
 * ============================================================
 *
 * Purpose:
 * Displays the security analysis generated by the
 * SEBAShield Link Checker service.
 *
 * Responsibilities:
 * - Display the analyzed URL.
 * - Display the calculated threat score.
 * - Display the overall risk classification.
 * - Display detected URL indicators.
 * - Provide clear safety recommendations.
 *
 * Navigation Flow:
 *
 * Home Screen
 *      ↓
 * Link Checker Screen
 *      ↓
 * Link Analysis Result Screen
 *
 * Author: Wubit
 * Project: SEBAShield Mobile Capstone
 * Technology: React Native + Expo
 * ============================================================
 */

import React from "react";

/**
 * React Native components used to build the result interface.
 *
 * View:
 * Groups related content.
 *
 * Text:
 * Displays labels and analysis information.
 *
 * ScrollView:
 * Allows long reports to scroll on smaller devices.
 *
 * StyleSheet:
 * Organizes the screen's visual styling.
 */
import {
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";

/**
 * Centralized application color palette.
 *
 * Using shared colors keeps the Link Result screen
 * visually consistent with the rest of SEBAShield.
 */
import { COLORS } from "../constants/colors";

/**
 * ============================================================
 * LinkResultScreen Component
 * ============================================================
 *
 * Receives linkAnalysisResult from LinkCheckerScreen
 * through React Navigation route parameters.
 */
export default function LinkResultScreen({ route }) {
  /**
   * Safely extract the analysis result.
   *
   * The fallback object prevents an application crash
   * if route parameters are missing.
   */
  const { linkAnalysisResult } = route.params || {};

  /**
   * Display a safe fallback screen when no result
   * was received from LinkCheckerScreen.
   */
  if (!linkAnalysisResult) {
    return (
      <View style={styles.fallbackContainer}>
        <Text style={styles.fallbackTitle}>
          No Link Analysis Available
        </Text>

        <Text style={styles.fallbackText}>
          Return to the Link Checker and submit a URL for analysis.
        </Text>
      </View>
    );
  }

  /**
   * Select the correct visual style based on the
   * calculated risk classification.
   */
  const getRiskStyle = () => {
    if (linkAnalysisResult.riskLevel === "High Risk") {
      return styles.highRisk;
    }

    if (linkAnalysisResult.riskLevel === "Suspicious") {
      return styles.suspicious;
    }

    return styles.safe;
  };

  /**
   * Select a user-friendly symbol for the risk level.
   */
  const getRiskIcon = () => {
    if (linkAnalysisResult.riskLevel === "High Risk") {
      return "🔴";
    }

    if (linkAnalysisResult.riskLevel === "Suspicious") {
      return "🟡";
    }

    return "🟢";
  };

  /**
   * Return recommendations that match the current risk.
   */
  const getRecommendations = () => {
    if (linkAnalysisResult.riskLevel === "High Risk") {
      return [
        "Do not open the link.",
        "Do not enter passwords or financial information.",
        "Delete or report the message containing the URL.",
        "Verify the sender through an official contact method.",
      ];
    }

    if (linkAnalysisResult.riskLevel === "Suspicious") {
      return [
        "Avoid opening the link until the sender is verified.",
        "Check the spelling of the domain carefully.",
        "Use the organization's official website instead.",
      ];
    }

    return [
      "No major rule-based indicators were detected.",
      "Continue to verify the sender before opening unfamiliar links.",
    ];
  };

  const recommendations = getRecommendations();

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
    >
      {/* Screen heading */}
      <Text style={styles.title}>
        🔗 Link Analysis
      </Text>

      {/* Threat score summary */}
      <View style={styles.scoreCard}>
        <Text style={styles.scoreLabel}>
          Threat Score
        </Text>

        <Text style={styles.scoreValue}>
          {linkAnalysisResult.score}%
        </Text>

        <Text style={[styles.riskLevel, getRiskStyle()]}>
          {getRiskIcon()} {linkAnalysisResult.riskLevel}
        </Text>
      </View>

      {/* Analyzed URL */}
      <Text style={styles.sectionTitle}>
        Analyzed URL
      </Text>

      <View style={styles.urlCard}>
        <Text style={styles.urlText}>
          {linkAnalysisResult.originalUrl}
        </Text>
      </View>

      {/* Detected indicators */}
      <Text style={styles.sectionTitle}>
        Detected Indicators
      </Text>

      {linkAnalysisResult.indicators.length === 0 ? (
        <Text style={styles.bodyText}>
          No common suspicious-link indicators were detected.
        </Text>
      ) : (
        linkAnalysisResult.indicators.map((indicator, index) => (
          <Text
            key={`${indicator}-${index}`}
            style={styles.indicator}
          >
            • {indicator}
          </Text>
        ))
      )}

      {/* Safety recommendations */}
      <Text style={styles.sectionTitle}>
        Safety Recommendations
      </Text>

      {recommendations.map((recommendation, index) => (
        <Text
          key={`${recommendation}-${index}`}
          style={styles.recommendation}
        >
          • {recommendation}
        </Text>
      ))}

      {/* Prototype disclaimer */}
      <View style={styles.noticeCard}>
        <Text style={styles.noticeTitle}>
          Important
        </Text>

        <Text style={styles.noticeText}>
          This result is based on rule-based URL analysis. A low score does not
          guarantee that a website is safe.
        </Text>
      </View>
    </ScrollView>
  );
}

/**
 * ============================================================
 * Screen Styles
 * ============================================================
 *
 * Defines the layout, typography, spacing, and risk colors
 * used by the Link Analysis Result screen.
 */
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  content: {
    padding: 20,
    paddingBottom: 40,
  },

  fallbackContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },

  fallbackTitle: {
    color: COLORS.text,
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
  },

  fallbackText: {
    color: COLORS.mutedText,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
    textAlign: "center",
  },

  title: {
    color: COLORS.text,
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 20,
  },

  scoreCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 18,
    alignItems: "center",
    padding: 22,
    marginBottom: 24,
  },

  scoreLabel: {
    color: COLORS.mutedText,
    fontSize: 16,
  },

  scoreValue: {
    color: COLORS.text,
    fontSize: 42,
    fontWeight: "bold",
    marginTop: 8,
  },

  riskLevel: {
    fontSize: 21,
    fontWeight: "bold",
    marginTop: 10,
  },

  highRisk: {
    color: COLORS.danger,
  },

  suspicious: {
    color: COLORS.warning,
  },

  safe: {
    color: COLORS.success,
  },

  sectionTitle: {
    color: COLORS.primary,
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 16,
    marginBottom: 10,
  },

  urlCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 15,
  },

  urlText: {
    color: COLORS.text,
    fontSize: 15,
    lineHeight: 22,
  },

  bodyText: {
    color: COLORS.text,
    fontSize: 15,
    lineHeight: 23,
  },

  indicator: {
    color: COLORS.text,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 8,
  },

  recommendation: {
    color: COLORS.text,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 8,
  },

  noticeCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.warning,
    borderWidth: 1,
    borderRadius: 12,
    marginTop: 24,
    padding: 16,
  },

  noticeTitle: {
    color: COLORS.warning,
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 6,
  },

  noticeText: {
    color: COLORS.mutedText,
    fontSize: 14,
    lineHeight: 21,
  },
});