/**
 * ============================================================
 * SEBAShield
 * Threat Analysis Result Screen
 * ============================================================
 *
 * Purpose:
 * Displays the scam analysis result generated by
 * the SEBAShield detection engine.
 *
 * Responsibilities:
 * - Show threat score
 * - Show risk level
 * - Show detected scam indicators
 * - Show the original submitted message
 *
 * Author: Wubit
 * Project: SEBAShield Mobile Capstone
 * ============================================================
 */

import React from "react";

import {
  View,
  Text,
  StyleSheet,
  ScrollView,
} from "react-native";

import { COLORS } from "../constants/colors";

/**
 * ResultScreen Component
 *
 * Receives analysisResult from ScannerScreen
 * through React Navigation route parameters.
 */
export default function ResultScreen({ route }) {
  const { analysisResult } = route.params || {};

  /**
   * Fallback UI if no analysis data is received.
   */
  if (!analysisResult) {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>No Analysis Available</Text>
      </View>
    );
  }

  /**
   * Selects color based on risk level.
   */
  const getRiskStyle = () => {
    if (analysisResult.riskLevel === "High Risk") {
      return styles.highRisk;
    }

    if (analysisResult.riskLevel === "Suspicious") {
      return styles.suspicious;
    }

    return styles.safe;
  };

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
    >
      <Text style={styles.title}>🛡️ Threat Analysis</Text>

      <View style={styles.scoreCard}>
        <Text style={styles.scoreLabel}>Threat Score</Text>

        <Text style={styles.scoreValue}>
          {analysisResult.score}%
        </Text>

        <Text style={[styles.riskLevel, getRiskStyle()]}>
          {analysisResult.riskLevel}
        </Text>
      </View>

      <Text style={styles.sectionTitle}>Detected Indicators</Text>

      {analysisResult.indicators.length === 0 ? (
        <Text style={styles.message}>
          No suspicious indicators were detected.
        </Text>
      ) : (
        analysisResult.indicators.map((indicator, index) => (
          <Text key={index} style={styles.indicator}>
            • {indicator}
          </Text>
        ))
      )}

      <Text style={styles.sectionTitle}>Submitted Message</Text>

      <Text style={styles.message}>
        {analysisResult.originalMessage}
      </Text>
    </ScrollView>
  );
}

/**
 * Screen Styles
 */
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  content: {
    padding: 20,
    paddingBottom: 40,
  },

  title: {
    color: COLORS.text,
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 20,
  },

  scoreCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 18,
    padding: 20,
    marginBottom: 24,
    alignItems: "center",
  },

  scoreLabel: {
    color: COLORS.mutedText,
    fontSize: 16,
  },

  scoreValue: {
    color: COLORS.text,
    fontSize: 42,
    fontWeight: "bold",
    marginTop: 8,
  },

  riskLevel: {
    fontSize: 22,
    fontWeight: "bold",
    marginTop: 10,
  },

  highRisk: {
    color: COLORS.danger,
  },

  suspicious: {
    color: COLORS.warning,
  },

  safe: {
    color: COLORS.success,
  },

  sectionTitle: {
    color: COLORS.primary,
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 16,
    marginBottom: 10,
  },

  indicator: {
    color: COLORS.text,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 8,
  },

  message: {
    color: COLORS.text,
    fontSize: 15,
    lineHeight: 24,
  },
});