/**
 * ============================================================
 * SEBAShield
 * Scan Application Service
 * ============================================================
 *
 * Purpose:
 * Coordinates the complete local scanning workflow for:
 * - Suspicious messages
 * - Suspicious links
 * - Fake job offers
 *
 * Responsibilities:
 * - Validate submitted content
 * - Select the correct cybersecurity analyzer
 * - Normalize analyzer results
 * - Generate safety recommendations
 * - Create a standardized scan record
 * - Save the scan through the local repository
 *
 * This service does not:
 * - Manage React component state
 * - Perform screen navigation
 * - Access AsyncStorage directly
 * - Communicate with Firebase directly
 *
 * Firebase synchronization is coordinated separately by
 * scanSyncService.js.
 * ============================================================
 */

import { analyzeMessage } from "../analyzers/messageScamAnalyzer";
import { analyzeLink } from "../analyzers/linkAnalyzer";
import { analyzeFakeJob } from "../analyzers/jobScamAnalyzer";

import {
  createScanRecord,
  SCAN_TYPES,
  SYNC_STATUS,
} from "../models/scanModel";

import {
  saveScan,
} from "../repositories/localScanRepository";

/**
 * Maximum amount of content accepted for one local analysis.
 *
 * This prevents unusually large submissions from consuming
 * unnecessary device resources.
 */
export const MAX_SCAN_CONTENT_LENGTH = 25000;

/**
 * Error codes exposed by the scan application service.
 */
export const SCAN_ERROR_CODES = Object.freeze({
  INVALID_REQUEST: "INVALID_REQUEST",
  EMPTY_CONTENT: "EMPTY_CONTENT",
  CONTENT_TOO_LONG: "CONTENT_TOO_LONG",
  UNSUPPORTED_SCAN_TYPE: "UNSUPPORTED_SCAN_TYPE",
  ANALYSIS_FAILED: "ANALYSIS_FAILED",
  SAVE_FAILED: "SAVE_FAILED",
});

/**
 * Structured error generated by the scan service.
 */
export class ScanServiceError extends Error {
  constructor(
    message,
    code,
    originalError = null
  ) {
    super(message);

    this.name = "ScanServiceError";
    this.code = code;
    this.originalError = originalError;
  }
}

/**
 * Returns true when a value is a plain object.
 */
function isPlainObject(value) {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value)
  );
}

/**
 * Converts supported scanner aliases into official
 * SEBAShield scan types.
 */
export function normalizeScanType(scanType) {
  if (typeof scanType !== "string") {
    return null;
  }

  const normalizedValue = scanType
    .trim()
    .toLowerCase()
    .replace(/_/g, "-");

  const aliases = {
    message: SCAN_TYPES.MESSAGE,
    text: SCAN_TYPES.MESSAGE,
    sms: SCAN_TYPES.MESSAGE,
    email: SCAN_TYPES.MESSAGE,

    link: SCAN_TYPES.LINK,
    url: SCAN_TYPES.LINK,
    website: SCAN_TYPES.LINK,

    "fake-job": SCAN_TYPES.FAKE_JOB,
    fakejob: SCAN_TYPES.FAKE_JOB,
    job: SCAN_TYPES.FAKE_JOB,
    employment: SCAN_TYPES.FAKE_JOB,
  };

  return aliases[normalizedValue] ?? null;
}

/**
 * Validates and normalizes submitted scan content.
 */
export function validateScanContent(content) {
  if (typeof content !== "string") {
    throw new ScanServiceError(
      "The submitted content must be text.",
      SCAN_ERROR_CODES.INVALID_REQUEST
    );
  }

  const normalizedContent =
    content.trim();

  if (!normalizedContent) {
    throw new ScanServiceError(
      "Enter content before starting the analysis.",
      SCAN_ERROR_CODES.EMPTY_CONTENT
    );
  }

  if (
    normalizedContent.length >
    MAX_SCAN_CONTENT_LENGTH
  ) {
    throw new ScanServiceError(
      `The submitted content exceeds the ${MAX_SCAN_CONTENT_LENGTH}-character limit.`,
      SCAN_ERROR_CODES.CONTENT_TOO_LONG
    );
  }

  return normalizedContent;
}

/**
 * Converts analyzer indicators into a clean string array.
 *
 * This also supports future analyzers that may return indicator
 * objects rather than strings.
 */
function normalizeIndicators(indicators) {
  if (!Array.isArray(indicators)) {
    return [];
  }

  return indicators
    .map((indicator) => {
      if (typeof indicator === "string") {
        return indicator.trim();
      }

      if (isPlainObject(indicator)) {
        const indicatorText =
          indicator.message ??
          indicator.description ??
          indicator.label ??
          indicator.title ??
          indicator.text;

        return typeof indicatorText === "string"
          ? indicatorText.trim()
          : "";
      }

      return "";
    })
    .filter(Boolean);
}

/**
 * Converts an analyzer score into an integer from 0 to 100.
 */
function normalizeAnalysisScore(score) {
  const numericScore =
    Number(score);

  if (!Number.isFinite(numericScore)) {
    return 0;
  }

  return Math.min(
    100,
    Math.max(
      0,
      Math.round(numericScore)
    )
  );
}

/**
 * Standardizes analyzer risk-level values.
 *
 * Existing SEBAShield user-facing labels such as:
 * - High Risk
 * - Suspicious
 *
 * are intentionally preserved.
 */
function normalizeRiskLevel(riskLevel) {
  if (
    typeof riskLevel !== "string" ||
    !riskLevel.trim()
  ) {
    return "Unknown";
  }

  const normalizedValue =
    riskLevel
      .trim()
      .toLowerCase();

  const knownLevels = {
    safe: "Safe",
    low: "Low",

    medium: "Medium",
    moderate: "Medium",

    suspicious: "Suspicious",

    high: "High",
    "high risk": "High Risk",

    critical: "Critical",

    unknown: "Unknown",
  };

  return (
    knownLevels[normalizedValue] ??
    riskLevel.trim()
  );
}

/**
 * Returns general safety recommendations based on risk level.
 *
 * These recommendations do not claim that submitted content is
 * definitely legitimate or fraudulent.
 */
function getGeneralRecommendations(
  riskLevel
) {
  const normalizedRiskLevel =
    normalizeRiskLevel(
      riskLevel
    ).toLowerCase();

  /**
   * High-risk results require immediate protective action.
   */
  if (
    normalizedRiskLevel === "critical" ||
    normalizedRiskLevel === "high" ||
    normalizedRiskLevel === "high risk"
  ) {
    return [
      "Do not reply, send money, open attachments, or provide personal information.",
      "Verify the sender or organization through an independently located official contact method.",
      "Save relevant evidence and report the incident through an appropriate official channel.",
    ];
  }

  /**
   * Suspicious and medium-risk results require independent
   * verification before the user follows the request.
   */
  if (
    normalizedRiskLevel === "suspicious" ||
    normalizedRiskLevel === "medium" ||
    normalizedRiskLevel === "moderate"
  ) {
    return [
      "Pause before taking any requested action.",
      "Independently verify the sender, organization, website, or offer.",
      "Do not provide passwords, financial information, identity documents, or verification codes.",
    ];
  }

  /**
   * Low-risk results still receive a caution because the local
   * rules cannot prove legitimacy.
   */
  return [
    "No strong indicators were detected by the current local rules, but this does not prove legitimacy.",
    "Continue cautiously and verify unexpected requests through official channels.",
  ];
}

/**
 * Returns recommendations specific to the selected scanner.
 */
function getScannerRecommendations(
  scanType,
  riskLevel
) {
  const recommendations =
    getGeneralRecommendations(
      riskLevel
    );

  if (
    scanType ===
    SCAN_TYPES.MESSAGE
  ) {
    recommendations.push(
      "Check the sender address or phone number carefully before responding."
    );
  }

  if (
    scanType ===
    SCAN_TYPES.LINK
  ) {
    recommendations.push(
      "Do not enter credentials or payment information until the website domain has been independently verified."
    );
  }

  if (
    scanType ===
    SCAN_TYPES.FAKE_JOB
  ) {
    recommendations.push(
      "Confirm the position on the employer's official careers website and contact the organization using independently verified information."
    );

    recommendations.push(
      "Legitimate employers should not require payment, gift cards, cryptocurrency, or sensitive banking information before employment is verified."
    );
  }

  /**
   * Set removes duplicate recommendations while preserving order.
   */
  return [
    ...new Set(
      recommendations
    ),
  ];
}

/**
 * Runs the suspicious-message analyzer and converts its response
 * into the standard SEBAShield analysis shape.
 */
function runMessageAnalysis(
  content
) {
  const analysis =
    analyzeMessage(content);

  return {
    score:
      normalizeAnalysisScore(
        analysis?.score
      ),

    riskLevel:
      normalizeRiskLevel(
        analysis?.riskLevel
      ),

    indicators:
      normalizeIndicators(
        analysis?.indicators
      ),

    originalContent:
      typeof analysis?.originalMessage ===
      "string"
        ? analysis.originalMessage
        : content,

    details: {
      analyzer:
        "messageScamAnalyzer",
    },
  };
}

/**
 * Runs the suspicious-link analyzer and normalizes its result.
 */
function runLinkAnalysis(
  content
) {
  const analysis =
    analyzeLink(content);

  return {
    score:
      normalizeAnalysisScore(
        analysis?.score
      ),

    riskLevel:
      normalizeRiskLevel(
        analysis?.riskLevel
      ),

    indicators:
      normalizeIndicators(
        analysis?.indicators
      ),

    originalContent:
      typeof analysis?.originalUrl ===
      "string"
        ? analysis.originalUrl
        : content,

    details: {
      analyzer:
        "linkAnalyzer",
    },
  };
}

/**
 * Runs the fake-job analyzer and normalizes its result.
 */
function runFakeJobAnalysis(
  content
) {
  const analysis =
    analyzeFakeJob(content);

  return {
    score:
      normalizeAnalysisScore(
        analysis?.score
      ),

    riskLevel:
      normalizeRiskLevel(
        analysis?.riskLevel
      ),

    indicators:
      normalizeIndicators(
        analysis?.indicators
      ),

    originalContent:
      typeof analysis?.originalContent ===
      "string"
        ? analysis.originalContent
        : content,

    details: {
      analyzer:
        "jobScamAnalyzer",

      requiresVerification:
        analysis?.requiresVerification !==
        false,
    },
  };
}

/**
 * Runs local analysis without saving the result.
 *
 * This function creates one consistent analysis contract for:
 * - Message Scanner
 * - Link Checker
 * - Fake Job Detector
 *
 * Future AI and threat-intelligence services can also build on
 * this standardized result.
 */
export function analyzeScan({
  scanType,
  content,
}) {
  const normalizedScanType =
    normalizeScanType(
      scanType
    );

  if (!normalizedScanType) {
    throw new ScanServiceError(
      `Unsupported scan type: ${scanType}`,
      SCAN_ERROR_CODES.UNSUPPORTED_SCAN_TYPE
    );
  }

  const normalizedContent =
    validateScanContent(
      content
    );

  try {
    let analysis;

    switch (
      normalizedScanType
    ) {
      case SCAN_TYPES.MESSAGE:
        analysis =
          runMessageAnalysis(
            normalizedContent
          );
        break;

      case SCAN_TYPES.LINK:
        analysis =
          runLinkAnalysis(
            normalizedContent
          );
        break;

      case SCAN_TYPES.FAKE_JOB:
        analysis =
          runFakeJobAnalysis(
            normalizedContent
          );
        break;

      default:
        throw new ScanServiceError(
          `Unsupported scan type: ${normalizedScanType}`,
          SCAN_ERROR_CODES.UNSUPPORTED_SCAN_TYPE
        );
    }

    const recommendations =
      getScannerRecommendations(
        normalizedScanType,
        analysis.riskLevel
      );

    return {
      scanType:
        normalizedScanType,

      ...analysis,

      recommendations,
    };
  } catch (error) {
    if (
      error instanceof
      ScanServiceError
    ) {
      throw error;
    }

    throw new ScanServiceError(
      "SEBAShield could not complete the analysis.",
      SCAN_ERROR_CODES.ANALYSIS_FAILED,
      error
    );
  }
}

/**
 * Runs the selected analyzer, creates the standardized local scan
 * record, and saves it through localScanRepository.
 *
 * Firebase synchronization happens later through ScanContext and
 * scanSyncService.
 */
export async function submitScan({
  scanType,
  content,
  ownerId = null,
  syncStatus =
    SYNC_STATUS.PENDING,
}) {
  /**
   * Complete local analysis first.
   */
  const analysis =
    analyzeScan({
      scanType,
      content,
    });

  /**
   * Convert the analysis into SEBAShield's persistent scan model.
   */
  const scanRecord =
    createScanRecord({
      ownerId,

      scanType:
        analysis.scanType,

      score:
        analysis.score,

      riskLevel:
        analysis.riskLevel,

      indicators:
        analysis.indicators,

      recommendations:
        analysis.recommendations,

      originalContent:
        analysis.originalContent,

      details:
        analysis.details,

      syncStatus,
    });

  /**
   * Local persistence happens before Firebase synchronization.
   *
   * This keeps SEBAShield usable even when the device is offline
   * or Firebase is temporarily unavailable.
   */
  try {
    await saveScan(
      scanRecord
    );
  } catch (error) {
    throw new ScanServiceError(
      "SEBAShield could not save the completed scan.",
      SCAN_ERROR_CODES.SAVE_FAILED,
      error
    );
  }

  return {
    analysis,
    scanRecord,
  };
}